name: Codecov
on:
  push:
    paths-ignore:
      - 'document/**'
  pull_request:
    paths-ignore:
      - 'document/**'
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
env:
  CI: GITHUB_ACTIONS
jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build KCode Coverage Report
        run: ./gradlew code-coverage-report:koverXmlReport --stacktrace

      - name: Upload KCode Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          files: ./code-coverage-report/build/reports/kover/report.xml
          path_to_write_report: ./coverage/codecov_report.txt